POST http://localhost:8080/articletype/adm
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTA1MTEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MzY5MTEsImlzcyI6Ikt1blV6VGVzdCJ9.7H3a5hsLvYtexUg3SM95PFzG20OlGWMZm4a-s7oEL1PWx1cvcMw4ZR__1KWbl7hbcGcV8xhhHwaPU3t2tZS-gQ

{
    "nameUz": "uuuu121",
  "nameRus": "rrrrr121",
  "nameEng": "eeeee121",
  "orderNumber": "12344511"
}

####
PUT http://localhost:8080/articletype/adm/articleTypeedit/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w


{

  "orderNumber": "12",
  "nameUz": "dddd",
  "nameRus": "aaa",
  "nameEng": "ffff"

}
####
DELETE http://localhost:8080/articletype/adm/articletypedelet/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w
###
GET http://localhost:8080/articletype/adm/pagination?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w
###
GET http://localhost:8080/articletype/adm/byLang?lang=uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w
