POST http://localhost:8080/articletype/adm
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODI5OTgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc0NjkzOTgsImlzcyI6Ikt1blV6VGVzdCJ9.hAghkpx-CmgwbYHAcNKK6NiaGFwx-RpBfaxheI_3kitUBm5Sej0JfUP8zrMoapl004fzzcX3O33eqfBKx6z7vg

{
    "nameUz": "uuuu6",
  "nameRus": "rrrrr6",
  "nameEng": "eeeee6",
  "orderNumber": "6"
}

####
PUT http://localhost:8080/articletype/adm/articleTypeedit/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w


{

  "orderNumber": "12",
  "nameUz": "dddd",
  "nameRus": "aaa",
  "nameEng": "ffff"

}
####
DELETE http://localhost:8080/articletype/adm/articletypedelet/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w
###
GET http://localhost:8080/articletype/adm/pagination?page=1&size=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w
###
GET http://localhost:8080/articletype/adm/byLang?lang=uz
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0NTM4NjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1NDAyNjQsImlzcyI6Ikt1blV6VGVzdCJ9.fMFSL5-u1e89CbP7Oc_Du4dwkHNNbHBnNbSbZePvbLi_b3Xz9nuJKf-9572MJ6Wmgfo6L9B3fDsXcgbGlEza5w
####
POST http://localhost:8080/articletype/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDYzMTMsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDkyNzEzLCJpc3MiOiJLdW5VelRlc3QifQ.6GSN4_ecHyLZ07CyPo7bV0EFhVcUHHY0JvL3lbFAiUsOVM7j44Y_GgW1htGaTDtqqOt8vlNATtv-NSSDtruz5g


{
  "orderNumber": "1",
  "nameUz": "UUUU",
  "nameRus": "RRRR",
  "nameEng": "EEEE"
}