POST http://localhost:8080/category/adm/created
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDYzMTMsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDkyNzEzLCJpc3MiOiJLdW5VelRlc3QifQ.6GSN4_ecHyLZ07CyPo7bV0EFhVcUHHY0JvL3lbFAiUsOVM7j44Y_GgW1htGaTDtqqOt8vlNATtv-NSSDtruz5g

{

  "nameUz": "cu1",
  "nameEng": "ce1",
  "nameRu": "cr1",
  "orderNumber": 0
}











