POST http://localhost:8080/region/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDczODExMjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc0Njc1MjgsImlzcyI6Ikt1blV6VGVzdCJ9.tjpX1azYIWT4_B1Cy7xc3XsqaA0AHwVG0bSrk8BvnrEDIvWc0bkaPW31p4y_rnIL0mJuDCe2BiDzSHpaTWC32Q

{
  "orderNumber": 24,
  "nameUz": "1-uz14",
  "nameRu": "1-ru14",
  "nameEn": "1-eng14"

}