POST http://localhost:8080/register/create
Content-Type: application/json

{
  "name": "Ozod",
  "surname": "Abjalilov",
  "email": "ozod@mail.ru",
  "password": "1234",
  "status": "ACTIVE",
  "role": "USER",
  "phone": "1111",
  "visible": false

}

###

POST http://localhost:8080/api/auth/registration
Content-Type: application/json

{
  "name": "Ozod",
  "phone": "998939559020",
  "surname": "abjalilov",
  "email": "ndjfjfjfjf",
  "password": "1234"
}

#### test
POST https://notify.eskiz.uz/api/auth/login
Content-Type: application/json

{
  "email": "abdujalilovozod95@gmail.com",
  "password": "q5CWpHHv8Y8EZ1FXx4FL2iIkjK4UfsT2Tn1NSTZF"
}





